/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* External globals from main module */
extern StradaValue *ARGV;
extern StradaValue *ARGC;
extern StradaValue *v_STDIN;
extern StradaValue *v_STDOUT;
extern StradaValue *v_STDERR;
extern StradaValue *__child_status;

/* Global variables and constants */
StradaValue *g_handler_fn = NULL;

StradaValue* cp_get(StradaValue* config, StradaValue* key);
StradaValue* cannoli_init(StradaValue* config);
StradaValue* cannoli_dispatch(StradaValue* c);

StradaValue* cp_get(StradaValue* config, StradaValue* key) {
strada_stack_push("cp_get", "cannoli_perla.strada");
strada_incref(config);
strada_cleanup_push(config);
strada_incref(key);
strada_cleanup_push(key);
StradaValue *kl = ({ StradaValue *__len_tmp = key; char *__len_str = strada_to_str_ss(__len_tmp); int64_t __len_res = strada_length(__len_str); strada_cstr_free(__len_str); strada_new_int(__len_res); });
StradaValue *cl = ({ StradaValue *__len_tmp = config; char *__len_str = strada_to_str_ss(__len_tmp); int64_t __len_res = strada_length(__len_str); strada_cstr_free(__len_str); strada_new_int(__len_res); });
StradaValue *i = strada_new_int(0);
while ((strada_to_int(i) < strada_to_int(cl))) {
    __redo_0: __attribute__((unused));
    while ((strada_to_int(i) < strada_to_int(cl))) {
        __redo_1: __attribute__((unused));
        StradaValue *ch = strada_substr(config, strada_to_int(i), 1);
        if (((({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(ch, ";")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }) && ({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(ch, " ")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) && ({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(ch, "\t")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }))) {
            strada_decref(ch);
            break;
        }
        ({ StradaValue *__old = i; i = STRADA_MAKE_TAGGED_INT(strada_to_int(i) + 1); strada_decref(__old); i; });
        strada_decref(ch);
    }
    if ((strada_to_int(i) >= strada_to_int(cl))) {
        break;
    }
    if (((strada_to_int(i) + strada_to_int(kl)) < strada_to_int(cl))) {
        StradaValue *head = strada_substr(config, strada_to_int(i), strada_to_int(kl));
        StradaValue *eq = strada_substr(config, (strada_to_int(i) + strada_to_int(kl)), 1);
        if ((({ StradaValue *__cond_tmp = ({ char *__cmp_ls = strada_to_str_ss(head); char *__cmp_rs = strada_to_str_ss(key); int __cmp_res = strcmp(__cmp_ls, __cmp_rs) == 0; strada_cstr_free(__cmp_ls); strada_cstr_free(__cmp_rs); strada_new_int(__cmp_res); }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }) && ({ StradaValue *__cond_tmp = strada_new_int(strada_str_eq_lit(eq, "=")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }))) {
            StradaValue *vs = STRADA_MAKE_TAGGED_INT((strada_to_int(i) + strada_to_int(kl)) + 1);
            StradaValue *ve = vs; strada_incref(ve);
            while ((strada_to_int(ve) < strada_to_int(cl))) {
                __redo_2: __attribute__((unused));
                if (({ StradaValue *__cond_tmp = ({ StradaValue *__cmp_l = strada_substr(config, strada_to_int(ve), 1); int __cmp_r = strada_str_eq_lit(__cmp_l, ";"); strada_decref(__cmp_l); strada_new_int(__cmp_r); }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
                    break;
                }
                ({ StradaValue *__old = ve; ve = STRADA_MAKE_TAGGED_INT(strada_to_int(ve) + 1); strada_decref(__old); ve; });
            }
            { StradaValue *__retval = strada_substr(config, strada_to_int(vs), (strada_to_int(ve) - strada_to_int(vs)));
                strada_decref(vs);
                strada_decref(ve);
                strada_decref(head);
                strada_decref(eq);
                strada_decref(kl);
                strada_decref(cl);
                strada_decref(i);
                strada_cleanup_pop();
                strada_decref(config);
                strada_cleanup_pop();
                strada_decref(key);
                strada_stack_pop();
                return __retval; }
            strada_decref(vs);
            strada_decref(ve);
        }
        strada_decref(head);
        strada_decref(eq);
    }
    while ((strada_to_int(i) < strada_to_int(cl))) {
        __redo_3: __attribute__((unused));
        if (({ StradaValue *__cond_tmp = ({ StradaValue *__cmp_l = strada_substr(config, strada_to_int(i), 1); int __cmp_r = strada_str_eq_lit(__cmp_l, ";"); strada_decref(__cmp_l); strada_new_int(__cmp_r); }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
            break;
        }
        ({ StradaValue *__old = i; i = STRADA_MAKE_TAGGED_INT(strada_to_int(i) + 1); strada_decref(__old); i; });
    }
}
{ StradaValue *__retval = strada_new_str("");
    strada_decref(kl);
    strada_decref(cl);
    strada_decref(i);
    strada_cleanup_pop();
    strada_decref(config);
    strada_cleanup_pop();
    strada_decref(key);
    strada_stack_pop();
    return __retval; }
strada_decref(kl);
strada_decref(cl);
strada_decref(i);
strada_cleanup_pop();
strada_decref(config);
strada_cleanup_pop();
strada_decref(key);
strada_stack_pop();
return strada_new_undef();
}


StradaValue* cannoli_init(StradaValue* config) {
strada_stack_push("cannoli_init", "cannoli_perla.strada");
strada_incref(config);
strada_cleanup_push(config);
StradaValue *so = ({ StradaValue *__arg1 = strada_new_str("so"); StradaValue *__call_result = cp_get(config, __arg1); strada_decref(__arg1); __call_result; });
StradaValue *init_name = ({ StradaValue *__arg1 = strada_new_str("init"); StradaValue *__call_result = cp_get(config, __arg1); strada_decref(__arg1); __call_result; });
StradaValue *handler_name = ({ StradaValue *__arg1 = strada_new_str("handler"); StradaValue *__call_result = cp_get(config, __arg1); strada_decref(__arg1); __call_result; });
if ((({ StradaValue *__num_tmp = ({ StradaValue *__len_tmp = so; char *__len_str = strada_to_str_ss(__len_tmp); int64_t __len_res = strada_length(__len_str); strada_cstr_free(__len_str); strada_new_int(__len_res); }); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }) == 0.0)) {
    ({ StradaValue *__say_tmp = strada_new_str("cannoli_perla: missing required `so=` option"); strada_say_fh(__say_tmp, v_STDERR); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_decref(so);
        strada_decref(init_name);
        strada_decref(handler_name);
        strada_cleanup_pop();
        strada_decref(config);
        strada_stack_pop();
        return __retval; }
}
if ((({ StradaValue *__num_tmp = ({ StradaValue *__len_tmp = handler_name; char *__len_str = strada_to_str_ss(__len_tmp); int64_t __len_res = strada_length(__len_str); strada_cstr_free(__len_str); strada_new_int(__len_res); }); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }) == 0.0)) {
    ({ StradaValue *__say_tmp = strada_new_str("cannoli_perla: missing required `handler=` option"); strada_say_fh(__say_tmp, v_STDERR); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_decref(so);
        strada_decref(init_name);
        strada_decref(handler_name);
        strada_cleanup_pop();
        strada_decref(config);
        strada_stack_pop();
        return __retval; }
}
StradaValue *lib = strada_dl_open(so);
if ((strada_to_int(lib) == 0)) {
    ({ StradaValue *__say_tmp = strada_concat_cstr_sv("cannoli_perla: could not dlopen ", 32, so); strada_say_fh(__say_tmp, v_STDERR); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_decref(so);
        strada_decref(init_name);
        strada_decref(handler_name);
        strada_decref(lib);
        strada_cleanup_pop();
        strada_decref(config);
        strada_stack_pop();
        return __retval; }
}
({ StradaValue *__say_tmp = strada_concat_cstr_sv("[cannoli_perla] loaded ", 23, so); strada_say_fh(__say_tmp, v_STDERR); strada_decref(__say_tmp); });
if ((({ StradaValue *__num_tmp = ({ StradaValue *__len_tmp = init_name; char *__len_str = strada_to_str_ss(__len_tmp); int64_t __len_res = strada_length(__len_str); strada_cstr_free(__len_str); strada_new_int(__len_res); }); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }) > 0.0)) {
    StradaValue *init_fn = strada_dl_sym(lib, init_name);
    if ((strada_to_int(init_fn) == 0)) {
        ({ StradaValue *__say_tmp = strada_concat_cstr_sv("cannoli_perla: init symbol not found: ", 38, init_name); strada_say_fh(__say_tmp, v_STDERR); strada_decref(__say_tmp); });
        { StradaValue *__retval = strada_new_int(0);
            strada_decref(init_fn);
            strada_decref(so);
            strada_decref(init_name);
            strada_decref(handler_name);
            strada_decref(lib);
            strada_cleanup_pop();
            strada_decref(config);
            strada_stack_pop();
            return __retval; }
    }
    strada_dl_call_int(init_fn, strada_new_str(""));
    ({ StradaValue *__say_tmp = strada_concat_cstr_sv("[cannoli_perla] init ", 21, init_name); strada_say_fh(__say_tmp, v_STDERR); strada_decref(__say_tmp); });
    strada_decref(init_fn);
}
({ StradaValue *__old = g_handler_fn; g_handler_fn = strada_dl_sym(lib, handler_name); strada_decref(__old); g_handler_fn; });
if ((strada_to_num(g_handler_fn) == 0.0)) {
    ({ StradaValue *__say_tmp = strada_concat_cstr_sv("cannoli_perla: handler symbol not found: ", 41, handler_name); strada_say_fh(__say_tmp, v_STDERR); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_decref(so);
        strada_decref(init_name);
        strada_decref(handler_name);
        strada_decref(lib);
        strada_cleanup_pop();
        strada_decref(config);
        strada_stack_pop();
        return __retval; }
}
({ StradaValue *__say_tmp = strada_concat_cstr_sv("[cannoli_perla] handler ", 24, handler_name); strada_say_fh(__say_tmp, v_STDERR); strada_decref(__say_tmp); });
{ StradaValue *__retval = strada_new_int(1);
    strada_decref(so);
    strada_decref(init_name);
    strada_decref(handler_name);
    strada_decref(lib);
    strada_cleanup_pop();
    strada_decref(config);
    strada_stack_pop();
    return __retval; }
strada_decref(so);
strada_decref(init_name);
strada_decref(handler_name);
strada_decref(lib);
strada_cleanup_pop();
strada_decref(config);
strada_stack_pop();
return strada_new_undef();
}


StradaValue* cannoli_dispatch(StradaValue* c) {
strada_stack_push("cannoli_dispatch", "cannoli_perla.strada");
strada_incref(c);
strada_cleanup_push(c);
if ((strada_to_num(g_handler_fn) == 0.0)) {
    { StradaValue *__retval = strada_new_str("");
        strada_cleanup_pop();
        strada_decref(c);
        strada_stack_pop();
        return __retval; }
}
StradaValue *empty_args = strada_anon_array(0);
StradaValue *result = ({ StradaValue *__dl_args = strada_anon_array(1, empty_args); StradaValue *__dl_res = strada_dl_call_sv(g_handler_fn, __dl_args); strada_decref(__dl_args); __dl_res; });
if (!(strada_defined_bool(result))) {
    { StradaValue *__retval = strada_new_str("");
        strada_decref(empty_args);
        strada_decref(result);
        strada_cleanup_pop();
        strada_decref(c);
        strada_stack_pop();
        return __retval; }
}
{ StradaValue *__retval = strada_concat_cstr_sv("", 0, result);
    strada_decref(empty_args);
    strada_decref(result);
    strada_cleanup_pop();
    strada_decref(c);
    strada_stack_pop();
    return __retval; }
strada_decref(empty_args);
strada_decref(result);
strada_cleanup_pop();
strada_decref(c);
strada_stack_pop();
return strada_new_undef();
}



/* Strada export metadata for import_lib */
const char* __strada_export_info(void) {
    return "func:cp_get:str:2:str,str:-1\nfunc:cannoli_init:int:1:str:-1\nfunc:cannoli_dispatch:str:1:scalar:-1\n";
}

/* Strada module version */
const char* __strada_version(void) {
    return "";
}

/* Shared library global initialization */
__attribute__((constructor))
static void __strada_init_globals(void) {
    if (g_handler_fn == NULL) {
        g_handler_fn = strada_new_int(0);
    }
}
