/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* External globals from main module */
extern StradaValue *ARGV;
extern StradaValue *ARGC;

/* Global variables */
StradaValue *g_perl_bridge = NULL;
StradaValue *g_handler_sub = NULL;
StradaValue *g_cannoli_pm_path = NULL;
StradaValue *g_init_fn = NULL;
StradaValue *g_add_inc_fn = NULL;
StradaValue *g_use_fn = NULL;
StradaValue *g_do_fn = NULL;
StradaValue *g_load_cannoli_fn = NULL;
StradaValue *g_call_handler_fn = NULL;

StradaValue* config_get(StradaValue* config, StradaValue* key);
StradaValue* config_get_all(StradaValue* config, StradaValue* key);
StradaValue* find_bridge_path(void);
StradaValue* find_cannoli_pm_path(void);
StradaValue* cannoli_init(StradaValue* config);
StradaValue* strada_dispatch_impl(StradaValue* method, StradaValue* path, StradaValue* path_info, StradaValue* query_string, StradaValue* body, StradaValue* headers, StradaValue* remote_addr, StradaValue* content_type);

StradaValue* config_get(StradaValue* config, StradaValue* key) {
StradaValue *key_len = strada_new_int(strada_length_sv(key));
StradaValue *config_len = strada_new_int(strada_length_sv(config));
StradaValue *i = strada_new_int(0);
while ((strada_to_num(i) < strada_to_num(config_len))) {
    while ((strada_to_num(i) < strada_to_num(config_len))) {
        StradaValue *ch = strada_substr(config, strada_to_int(i), strada_to_int(strada_new_int(1)));
        if (((strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) != 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(" "))) != 0))) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\t"))) != 0)))) {
            break;
        }
        ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
        strada_decref(ch);
    }
    if ((strada_to_num(i) >= strada_to_num(config_len))) {
        break;
    }
    if ((strada_to_num(strada_new_num(strada_to_num(i) + strada_to_num(key_len))) < strada_to_num(config_len))) {
        StradaValue *maybe_key = strada_substr(config, strada_to_int(i), strada_to_int(key_len));
        StradaValue *after_key = strada_substr(config, strada_to_int(strada_new_num(strada_to_num(i) + strada_to_num(key_len))), strada_to_int(strada_new_int(1)));
        if ((strada_to_bool(strada_new_int(strcmp(strada_to_str(maybe_key), strada_to_str(key)) == 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(after_key), strada_to_str(strada_new_str("="))) == 0)))) {
            StradaValue *value_start = strada_new_num(strada_to_num(strada_new_num(strada_to_num(i) + strada_to_num(key_len))) + 1.0);
            StradaValue *value_end = value_start; strada_incref(value_end);
            while ((strada_to_num(value_end) < strada_to_num(config_len))) {
                StradaValue *ch = strada_substr(config, strada_to_int(value_end), strada_to_int(strada_new_int(1)));
                if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) == 0))) {
                    break;
                }
                ({ StradaValue *__old = value_end; value_end = strada_new_num(strada_to_num(value_end) + 1.0); strada_decref(__old); value_end; });
                strada_decref(ch);
            }
            { StradaValue *__retval = strada_substr(config, strada_to_int(value_start), strada_to_int(strada_new_num(strada_to_num(value_end) - strada_to_num(value_start))));
                strada_decref(value_start);
                strada_decref(value_end);
                strada_decref(maybe_key);
                strada_decref(after_key);
                strada_decref(key_len);
                strada_decref(config_len);
                strada_decref(i);
                return __retval; }
            strada_decref(value_start);
            strada_decref(value_end);
        }
        strada_decref(maybe_key);
        strada_decref(after_key);
    }
    while ((strada_to_num(i) < strada_to_num(config_len))) {
        StradaValue *ch = strada_substr(config, strada_to_int(i), strada_to_int(strada_new_int(1)));
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) == 0))) {
            break;
        }
        ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
        strada_decref(ch);
    }
}
{ StradaValue *__retval = strada_new_str("");
    strada_decref(key_len);
    strada_decref(config_len);
    strada_decref(i);
    return __retval; }
strada_decref(key_len);
strada_decref(config_len);
strada_decref(i);
}


StradaValue* config_get_all(StradaValue* config, StradaValue* key) {
StradaValue *values = strada_new_array();
StradaValue *key_len = strada_new_int(strada_length_sv(key));
StradaValue *config_len = strada_new_int(strada_length_sv(config));
StradaValue *i = strada_new_int(0);
while ((strada_to_num(i) < strada_to_num(config_len))) {
    while ((strada_to_num(i) < strada_to_num(config_len))) {
        StradaValue *ch = strada_substr(config, strada_to_int(i), strada_to_int(strada_new_int(1)));
        if (((strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) != 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(" "))) != 0))) && strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str("\t"))) != 0)))) {
            break;
        }
        ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
        strada_decref(ch);
    }
    if ((strada_to_num(i) >= strada_to_num(config_len))) {
        break;
    }
    if ((strada_to_num(strada_new_num(strada_to_num(i) + strada_to_num(key_len))) < strada_to_num(config_len))) {
        StradaValue *maybe_key = strada_substr(config, strada_to_int(i), strada_to_int(key_len));
        StradaValue *after_key = strada_substr(config, strada_to_int(strada_new_num(strada_to_num(i) + strada_to_num(key_len))), strada_to_int(strada_new_int(1)));
        if ((strada_to_bool(strada_new_int(strcmp(strada_to_str(maybe_key), strada_to_str(key)) == 0)) && strada_to_bool(strada_new_int(strcmp(strada_to_str(after_key), strada_to_str(strada_new_str("="))) == 0)))) {
            StradaValue *value_start = strada_new_num(strada_to_num(strada_new_num(strada_to_num(i) + strada_to_num(key_len))) + 1.0);
            StradaValue *value_end = value_start; strada_incref(value_end);
            while ((strada_to_num(value_end) < strada_to_num(config_len))) {
                StradaValue *ch = strada_substr(config, strada_to_int(value_end), strada_to_int(strada_new_int(1)));
                if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) == 0))) {
                    break;
                }
                ({ StradaValue *__old = value_end; value_end = strada_new_num(strada_to_num(value_end) + 1.0); strada_decref(__old); value_end; });
                strada_decref(ch);
            }
            StradaValue *value = strada_substr(config, strada_to_int(value_start), strada_to_int(strada_new_num(strada_to_num(value_end) - strada_to_num(value_start))));
            (strada_array_push(strada_deref_array(strada_new_ref(values, '@')), value), strada_new_undef());
            strada_decref(value_start);
            strada_decref(value_end);
            strada_decref(value);
        }
        strada_decref(maybe_key);
        strada_decref(after_key);
    }
    while ((strada_to_num(i) < strada_to_num(config_len))) {
        StradaValue *ch = strada_substr(config, strada_to_int(i), strada_to_int(strada_new_int(1)));
        if (strada_to_bool(strada_new_int(strcmp(strada_to_str(ch), strada_to_str(strada_new_str(";"))) == 0))) {
            break;
        }
        ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
        strada_decref(ch);
    }
}
{ StradaValue *__retval = values;
    strada_incref(__retval);
    strada_decref(values);
    strada_decref(key_len);
    strada_decref(config_len);
    strada_decref(i);
    return __retval; }
strada_decref(values);
strada_decref(key_len);
strada_decref(config_len);
strada_decref(i);
}


StradaValue* find_bridge_path(void) {
if (strada_to_bool(strada_is_file(strada_new_str("./lib/perl/libperl_bridge.so")))) {
    { StradaValue *__retval = strada_new_str("./lib/perl/libperl_bridge.so");
        return __retval; }
}
if (strada_to_bool(strada_is_file(strada_new_str("./cannoli/lib/perl/libperl_bridge.so")))) {
    { StradaValue *__retval = strada_new_str("./cannoli/lib/perl/libperl_bridge.so");
        return __retval; }
}
if (strada_to_bool(strada_is_file(strada_new_str("/usr/local/lib/cannoli/libperl_bridge.so")))) {
    { StradaValue *__retval = strada_new_str("/usr/local/lib/cannoli/libperl_bridge.so");
        return __retval; }
}
{ StradaValue *__retval = strada_new_str("libperl_bridge.so");
    return __retval; }
}


StradaValue* find_cannoli_pm_path(void) {
if (strada_to_bool(strada_is_file(strada_new_str("./lib/perl/Cannoli.pm")))) {
    { StradaValue *__retval = strada_new_str("./lib/perl/Cannoli.pm");
        return __retval; }
}
if (strada_to_bool(strada_is_file(strada_new_str("./cannoli/lib/perl/Cannoli.pm")))) {
    { StradaValue *__retval = strada_new_str("./cannoli/lib/perl/Cannoli.pm");
        return __retval; }
}
if (strada_to_bool(strada_is_file(strada_new_str("/usr/local/lib/cannoli/Cannoli.pm")))) {
    { StradaValue *__retval = strada_new_str("/usr/local/lib/cannoli/Cannoli.pm");
        return __retval; }
}
{ StradaValue *__retval = strada_new_str("");
    return __retval; }
}


StradaValue* cannoli_init(StradaValue* config) {
({ StradaValue *__old = g_handler_sub; g_handler_sub = ({ StradaValue *__arg1 = strada_new_str("handler"); StradaValue *__call_result = config_get(config, __arg1); strada_decref(__arg1); __call_result; }); strada_decref(__old); g_handler_sub; });
if ((strada_to_num(strada_new_int(strada_length_sv(g_handler_sub))) == 0.0)) {
    ({ StradaValue *__say_tmp = strada_new_str("cannoli_perl: ERROR - Missing required 'handler' parameter"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    ({ StradaValue *__say_tmp = strada_new_str("Usage: --library ./cannoli_perl.so:handler=MyApp::handle"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        return __retval; }
}
StradaValue *bridge_path = find_bridge_path();
({ StradaValue *__old = g_perl_bridge; g_perl_bridge = strada_dl_open(bridge_path); strada_decref(__old); g_perl_bridge; });
if ((strada_to_num(g_perl_bridge) == 0.0)) {
    ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("cannoli_perl: ERROR - Could not load "); StradaValue *__concat_res = strada_concat_sv(__concat_l, bridge_path); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
    ({ StradaValue *__say_tmp = strada_new_str("  Make sure libperl_bridge.so is built and accessible"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_decref(bridge_path);
        return __retval; }
}
({ StradaValue *__old = g_init_fn; g_init_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_init")); strada_decref(__old); g_init_fn; });
({ StradaValue *__old = g_add_inc_fn; g_add_inc_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_add_inc")); strada_decref(__old); g_add_inc_fn; });
({ StradaValue *__old = g_use_fn; g_use_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_use")); strada_decref(__old); g_use_fn; });
({ StradaValue *__old = g_do_fn; g_do_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_do")); strada_decref(__old); g_do_fn; });
({ StradaValue *__old = g_load_cannoli_fn; g_load_cannoli_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_load_cannoli")); strada_decref(__old); g_load_cannoli_fn; });
({ StradaValue *__old = g_call_handler_fn; g_call_handler_fn = strada_dl_sym(g_perl_bridge, strada_new_str("perl_bridge_call_handler")); strada_decref(__old); g_call_handler_fn; });
if (((strada_to_num(g_init_fn) == 0.0) || (strada_to_num(g_call_handler_fn) == 0.0))) {
    ({ StradaValue *__say_tmp = strada_new_str("cannoli_perl: ERROR - Bridge functions not found"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_decref(bridge_path);
        return __retval; }
}
StradaValue *init_result = strada_dl_call_int(g_init_fn, strada_new_str("init"));
if ((strada_to_num(init_result) == 0.0)) {
    ({ StradaValue *__say_tmp = strada_new_str("cannoli_perl: ERROR - Perl initialization failed"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_decref(bridge_path);
        strada_decref(init_result);
        return __retval; }
}
StradaValue *lib_paths = ({ StradaValue *__arg1 = strada_new_str("lib"); StradaValue *__call_result = config_get_all(config, __arg1); strada_decref(__arg1); __call_result; });
StradaValue *i = strada_new_int(0);
while ((strada_to_num(i) < strada_to_num(strada_new_int(strada_array_length(strada_deref_array(lib_paths)))))) {
    StradaValue *lib_path = strada_array_get(strada_deref_array(lib_paths), strada_to_int(i)); strada_incref(lib_path);
    strada_dl_call_int_sv(g_add_inc_fn, strada_anon_array(1, lib_path));
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(lib_path);
}
({ StradaValue *__old = g_cannoli_pm_path; g_cannoli_pm_path = find_cannoli_pm_path(); strada_decref(__old); g_cannoli_pm_path; });
if ((strada_to_num(g_load_cannoli_fn) != 0.0)) {
    StradaValue *load_result = strada_dl_call_int_sv(g_load_cannoli_fn, strada_anon_array(1, g_cannoli_pm_path));
    if ((strada_to_num(load_result) == 0.0)) {
        ({ StradaValue *__say_tmp = strada_new_str("cannoli_perl: ERROR - Failed to load Cannoli.pm"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        { StradaValue *__retval = strada_new_int(0);
            strada_decref(load_result);
            strada_decref(bridge_path);
            strada_decref(init_result);
            strada_decref(lib_paths);
            strada_decref(i);
            return __retval; }
    }
    strada_decref(load_result);
}
StradaValue *modules = ({ StradaValue *__arg1 = strada_new_str("use"); StradaValue *__call_result = config_get_all(config, __arg1); strada_decref(__arg1); __call_result; });
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < strada_to_num(strada_new_int(strada_array_length(strada_deref_array(modules)))))) {
    StradaValue *module = strada_array_get(strada_deref_array(modules), strada_to_int(i)); strada_incref(module);
    StradaValue *use_result = strada_dl_call_int_sv(g_use_fn, strada_anon_array(1, module));
    if ((strada_to_num(use_result) == 0.0)) {
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("cannoli_perl: ERROR - Failed to use "); StradaValue *__concat_res = strada_concat_sv(__concat_l, module); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
        { StradaValue *__retval = strada_new_int(0);
            strada_decref(module);
            strada_decref(use_result);
            strada_decref(bridge_path);
            strada_decref(init_result);
            strada_decref(lib_paths);
            strada_decref(i);
            strada_decref(modules);
            return __retval; }
    }
    ({ StradaValue *__old = i; i = strada_new_num(strada_to_num(i) + 1.0); strada_decref(__old); i; });
    strada_decref(module);
    strada_decref(use_result);
}
StradaValue *script = ({ StradaValue *__arg1 = strada_new_str("script"); StradaValue *__call_result = config_get(config, __arg1); strada_decref(__arg1); __call_result; });
if ((strada_to_num(strada_new_int(strada_length_sv(script))) > 0.0)) {
    StradaValue *do_result = strada_dl_call_int_sv(g_do_fn, strada_anon_array(1, script));
    if ((strada_to_num(do_result) == 0.0)) {
        ({ StradaValue *__say_tmp = ({ StradaValue *__concat_l = strada_new_str("cannoli_perl: ERROR - Failed to load "); StradaValue *__concat_res = strada_concat_sv(__concat_l, script); strada_decref(__concat_l); __concat_res; }); strada_say(__say_tmp); strada_decref(__say_tmp); });
        { StradaValue *__retval = strada_new_int(0);
            strada_decref(do_result);
            strada_decref(bridge_path);
            strada_decref(init_result);
            strada_decref(lib_paths);
            strada_decref(i);
            strada_decref(modules);
            strada_decref(script);
            return __retval; }
    }
    strada_decref(do_result);
}
{ StradaValue *__retval = strada_new_int(1);
    strada_decref(bridge_path);
    strada_decref(init_result);
    strada_decref(lib_paths);
    strada_decref(i);
    strada_decref(modules);
    strada_decref(script);
    return __retval; }
strada_decref(bridge_path);
strada_decref(init_result);
strada_decref(lib_paths);
strada_decref(i);
strada_decref(modules);
strada_decref(script);
}


StradaValue* strada_dispatch_impl(StradaValue* method, StradaValue* path, StradaValue* path_info, StradaValue* query_string, StradaValue* body, StradaValue* headers, StradaValue* remote_addr, StradaValue* content_type) {
if (((strada_to_num(g_call_handler_fn) == 0.0) || (strada_to_num(strada_new_int(strada_length_sv(g_handler_sub))) == 0.0))) {
    { StradaValue *__retval = strada_new_str("");
        return __retval; }
}
StradaValue *result = strada_dl_call_str_sv(g_call_handler_fn, strada_anon_array(9, g_handler_sub, method, path, path_info, query_string, body, headers, remote_addr, content_type));
{ StradaValue *__retval = result;
    strada_incref(__retval);
    strada_decref(result);
    return __retval; }
strada_decref(result);
}



/* Strada export metadata for import_lib */
const char* __strada_export_info(void) {
    return "func:config_get:str:2:str,str\nfunc:config_get_all:array:2:str,str\nfunc:find_bridge_path:str:0:\nfunc:find_cannoli_pm_path:str:0:\nfunc:cannoli_init:int:1:str\nfunc:strada_dispatch_impl:str:8:str,str,str,str,str,str,str,str\n";
}

/* Strada module version */
const char* __strada_version(void) {
    return "";
}
