/* Generated by Strada Self-Hosting Compiler */
#include "strada_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <dlfcn.h>
#include <math.h>

/* External globals from main module */
extern StradaValue *ARGV;
extern StradaValue *ARGC;
extern StradaValue *v_STDIN;
extern StradaValue *v_STDOUT;
extern StradaValue *v_STDERR;
extern StradaValue *__child_status;

/* Global variables and constants */
StradaValue *g_perl_bridge = NULL;
StradaValue *g_handler_sub = NULL;
StradaValue *g_cannoli_pm_path = NULL;
StradaValue *g_init_fn = NULL;
StradaValue *g_add_inc_fn = NULL;
StradaValue *g_use_fn = NULL;
StradaValue *g_do_fn = NULL;
StradaValue *g_load_cannoli_fn = NULL;
StradaValue *g_call_handler_fn = NULL;

StradaValue* config_get(StradaValue* config, StradaValue* key);
StradaValue* config_get_all(StradaValue* config, StradaValue* key);
StradaValue* find_bridge_path(void);
StradaValue* find_cannoli_pm_path(void);
StradaValue* cannoli_init(StradaValue* config);
StradaValue* cannoli_dispatch(StradaValue* c);

StradaValue* config_get(StradaValue* config, StradaValue* key) {
strada_stack_push("config_get", "cannoli_perl.strada");
strada_incref(config);
strada_cleanup_push(config);
strada_incref(key);
strada_cleanup_push(key);
StradaValue *key_len = ({ StradaValue *__len_tmp = key; int64_t __len_res = strada_length_chars_sv(__len_tmp); strada_new_int(__len_res); });
strada_cleanup_push(key_len);
StradaValue *config_len = ({ StradaValue *__len_tmp = config; int64_t __len_res = strada_length_chars_sv(__len_tmp); strada_new_int(__len_res); });
strada_cleanup_push(config_len);
StradaValue *i = strada_new_int(0);
strada_cleanup_push(i);
while ((strada_to_int(i) < strada_to_int(config_len))) {
    __redo_0: __attribute__((unused));
    while ((strada_to_int(i) < strada_to_int(config_len))) {
        __redo_1: __attribute__((unused));
        StradaValue *ch = strada_substr(config, strada_to_int(i), 1);
        strada_cleanup_push(ch);
        if (((({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(ch, ";")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }) && ({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(ch, " ")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) && ({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(ch, "\t")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }))) {
            strada_cleanup_pop(); strada_decref(ch);
            break;
        }
        ({ StradaValue *__old = i; i = STRADA_MAKE_TAGGED_INT(strada_to_int(i) + 1); strada_decref(__old); i; });
        strada_break_self_cycle(ch);
        strada_cleanup_pop(); strada_decref(ch);
    }
    if ((strada_to_int(i) >= strada_to_int(config_len))) {
        break;
    }
    if (((strada_to_int(i) + strada_to_int(key_len)) < strada_to_int(config_len))) {
        StradaValue *maybe_key = strada_substr(config, strada_to_int(i), strada_to_int(key_len));
        strada_cleanup_push(maybe_key);
        StradaValue *after_key = strada_substr(config, (strada_to_int(i) + strada_to_int(key_len)), 1);
        strada_cleanup_push(after_key);
        if ((({ StradaValue *__cond_tmp = ({ char *__cmp_ls = strada_to_str_ss(maybe_key); char *__cmp_rs = strada_to_str_ss(key); int __cmp_res = strcmp(__cmp_ls, __cmp_rs) == 0; strada_cstr_free(__cmp_ls); strada_cstr_free(__cmp_rs); strada_new_int(__cmp_res); }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }) && ({ StradaValue *__cond_tmp = strada_new_int(strada_str_eq_lit(after_key, "=")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }))) {
            StradaValue *value_start = STRADA_MAKE_TAGGED_INT((strada_to_int(i) + strada_to_int(key_len)) + 1);
            strada_cleanup_push(value_start);
            StradaValue *value_end = value_start; strada_incref(value_end);
            strada_cleanup_push(value_end);
            while ((strada_to_int(value_end) < strada_to_int(config_len))) {
                __redo_2: __attribute__((unused));
                StradaValue *ch = strada_substr(config, strada_to_int(value_end), 1);
                strada_cleanup_push(ch);
                if (({ StradaValue *__cond_tmp = strada_new_int(strada_str_eq_lit(ch, ";")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
                    strada_cleanup_pop(); strada_decref(ch);
                    break;
                }
                ({ StradaValue *__old = value_end; value_end = STRADA_MAKE_TAGGED_INT(strada_to_int(value_end) + 1); strada_decref(__old); value_end; });
                strada_break_self_cycle(ch);
                strada_cleanup_pop(); strada_decref(ch);
            }
            { StradaValue *__retval = strada_substr(config, strada_to_int(value_start), (strada_to_int(value_end) - strada_to_int(value_start)));
                strada_cleanup_pop(); strada_decref(value_start);
                strada_cleanup_pop(); strada_decref(value_end);
                strada_cleanup_pop(); strada_decref(maybe_key);
                strada_cleanup_pop(); strada_decref(after_key);
                strada_cleanup_pop(); strada_decref(key_len);
                strada_cleanup_pop(); strada_decref(config_len);
                strada_cleanup_pop(); strada_decref(i);
                strada_cleanup_pop();
                strada_decref(config);
                strada_cleanup_pop();
                strada_decref(key);
                strada_stack_pop();
                return __retval; }
            strada_break_self_cycle(value_start);
            strada_break_self_cycle(value_end);
            strada_cleanup_pop(); strada_decref(value_start);
            strada_cleanup_pop(); strada_decref(value_end);
        }
        strada_break_self_cycle(maybe_key);
        strada_break_self_cycle(after_key);
        strada_cleanup_pop(); strada_decref(maybe_key);
        strada_cleanup_pop(); strada_decref(after_key);
    }
    while ((strada_to_int(i) < strada_to_int(config_len))) {
        __redo_3: __attribute__((unused));
        StradaValue *ch = strada_substr(config, strada_to_int(i), 1);
        strada_cleanup_push(ch);
        if (({ StradaValue *__cond_tmp = strada_new_int(strada_str_eq_lit(ch, ";")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
            strada_cleanup_pop(); strada_decref(ch);
            break;
        }
        ({ StradaValue *__old = i; i = STRADA_MAKE_TAGGED_INT(strada_to_int(i) + 1); strada_decref(__old); i; });
        strada_break_self_cycle(ch);
        strada_cleanup_pop(); strada_decref(ch);
    }
}
{ StradaValue *__retval = STRADA_NEW_STR_LIT("");
    strada_cleanup_pop(); strada_decref(key_len);
    strada_cleanup_pop(); strada_decref(config_len);
    strada_cleanup_pop(); strada_decref(i);
    strada_cleanup_pop();
    strada_decref(config);
    strada_cleanup_pop();
    strada_decref(key);
    strada_stack_pop();
    return __retval; }
strada_break_self_cycle(key_len);
strada_break_self_cycle(config_len);
strada_break_self_cycle(i);
strada_cleanup_pop(); strada_decref(key_len);
strada_cleanup_pop(); strada_decref(config_len);
strada_cleanup_pop(); strada_decref(i);
strada_cleanup_pop();
strada_decref(config);
strada_cleanup_pop();
strada_decref(key);
strada_stack_pop();
return strada_new_undef();
}


StradaValue* config_get_all(StradaValue* config, StradaValue* key) {
strada_stack_push("config_get_all", "cannoli_perl.strada");
strada_incref(config);
strada_cleanup_push(config);
strada_incref(key);
strada_cleanup_push(key);
StradaValue *values = strada_new_array();
strada_cleanup_push(values);
StradaValue *key_len = ({ StradaValue *__len_tmp = key; int64_t __len_res = strada_length_chars_sv(__len_tmp); strada_new_int(__len_res); });
strada_cleanup_push(key_len);
StradaValue *config_len = ({ StradaValue *__len_tmp = config; int64_t __len_res = strada_length_chars_sv(__len_tmp); strada_new_int(__len_res); });
strada_cleanup_push(config_len);
StradaValue *i = strada_new_int(0);
strada_cleanup_push(i);
while ((strada_to_int(i) < strada_to_int(config_len))) {
    __redo_4: __attribute__((unused));
    while ((strada_to_int(i) < strada_to_int(config_len))) {
        __redo_5: __attribute__((unused));
        StradaValue *ch = strada_substr(config, strada_to_int(i), 1);
        strada_cleanup_push(ch);
        if (((({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(ch, ";")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }) && ({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(ch, " ")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) && ({ StradaValue *__cond_tmp = strada_new_int(strada_str_ne_lit(ch, "\t")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }))) {
            strada_cleanup_pop(); strada_decref(ch);
            break;
        }
        ({ StradaValue *__old = i; i = STRADA_MAKE_TAGGED_INT(strada_to_int(i) + 1); strada_decref(__old); i; });
        strada_break_self_cycle(ch);
        strada_cleanup_pop(); strada_decref(ch);
    }
    if ((strada_to_int(i) >= strada_to_int(config_len))) {
        break;
    }
    if (((strada_to_int(i) + strada_to_int(key_len)) < strada_to_int(config_len))) {
        StradaValue *maybe_key = strada_substr(config, strada_to_int(i), strada_to_int(key_len));
        strada_cleanup_push(maybe_key);
        StradaValue *after_key = strada_substr(config, (strada_to_int(i) + strada_to_int(key_len)), 1);
        strada_cleanup_push(after_key);
        if ((({ StradaValue *__cond_tmp = ({ char *__cmp_ls = strada_to_str_ss(maybe_key); char *__cmp_rs = strada_to_str_ss(key); int __cmp_res = strcmp(__cmp_ls, __cmp_rs) == 0; strada_cstr_free(__cmp_ls); strada_cstr_free(__cmp_rs); strada_new_int(__cmp_res); }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }) && ({ StradaValue *__cond_tmp = strada_new_int(strada_str_eq_lit(after_key, "=")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; }))) {
            StradaValue *value_start = STRADA_MAKE_TAGGED_INT((strada_to_int(i) + strada_to_int(key_len)) + 1);
            strada_cleanup_push(value_start);
            StradaValue *value_end = value_start; strada_incref(value_end);
            strada_cleanup_push(value_end);
            while ((strada_to_int(value_end) < strada_to_int(config_len))) {
                __redo_6: __attribute__((unused));
                StradaValue *ch = strada_substr(config, strada_to_int(value_end), 1);
                strada_cleanup_push(ch);
                if (({ StradaValue *__cond_tmp = strada_new_int(strada_str_eq_lit(ch, ";")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
                    strada_cleanup_pop(); strada_decref(ch);
                    break;
                }
                ({ StradaValue *__old = value_end; value_end = STRADA_MAKE_TAGGED_INT(strada_to_int(value_end) + 1); strada_decref(__old); value_end; });
                strada_break_self_cycle(ch);
                strada_cleanup_pop(); strada_decref(ch);
            }
            StradaValue *value = strada_substr(config, strada_to_int(value_start), (strada_to_int(value_end) - strada_to_int(value_start)));
            strada_cleanup_push(value);
            ({ StradaValue *__expr_tmp = ({ StradaValue *__push_a = strada_new_ref(values, '@'); StradaArray *__push_av = strada_deref_array(__push_a); strada_array_push(__push_av, value); strada_decref(__push_a); strada_undef_static(); }); strada_decref(__expr_tmp); });
            strada_break_self_cycle(value_start);
            strada_break_self_cycle(value_end);
            strada_break_self_cycle(value);
            strada_cleanup_pop(); strada_decref(value_start);
            strada_cleanup_pop(); strada_decref(value_end);
            strada_cleanup_pop(); strada_decref(value);
        }
        strada_break_self_cycle(maybe_key);
        strada_break_self_cycle(after_key);
        strada_cleanup_pop(); strada_decref(maybe_key);
        strada_cleanup_pop(); strada_decref(after_key);
    }
    while ((strada_to_int(i) < strada_to_int(config_len))) {
        __redo_7: __attribute__((unused));
        StradaValue *ch = strada_substr(config, strada_to_int(i), 1);
        strada_cleanup_push(ch);
        if (({ StradaValue *__cond_tmp = strada_new_int(strada_str_eq_lit(ch, ";")); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
            strada_cleanup_pop(); strada_decref(ch);
            break;
        }
        ({ StradaValue *__old = i; i = STRADA_MAKE_TAGGED_INT(strada_to_int(i) + 1); strada_decref(__old); i; });
        strada_break_self_cycle(ch);
        strada_cleanup_pop(); strada_decref(ch);
    }
}
{ StradaValue *__retval = values;
    strada_incref(__retval);
    strada_cleanup_pop(); strada_decref(values);
    strada_cleanup_pop(); strada_decref(key_len);
    strada_cleanup_pop(); strada_decref(config_len);
    strada_cleanup_pop(); strada_decref(i);
    strada_cleanup_pop();
    strada_decref(config);
    strada_cleanup_pop();
    strada_decref(key);
    strada_stack_pop();
    return __retval; }
strada_break_self_cycle(values);
strada_break_self_cycle(key_len);
strada_break_self_cycle(config_len);
strada_break_self_cycle(i);
strada_cleanup_pop(); strada_decref(values);
strada_cleanup_pop(); strada_decref(key_len);
strada_cleanup_pop(); strada_decref(config_len);
strada_cleanup_pop(); strada_decref(i);
strada_cleanup_pop();
strada_decref(config);
strada_cleanup_pop();
strada_decref(key);
strada_stack_pop();
return strada_new_undef();
}


StradaValue* find_bridge_path(void) {
strada_stack_push("find_bridge_path", "cannoli_perl.strada");
if (({ StradaValue *__cond_tmp = ({ StradaValue *__call_arg0 = STRADA_NEW_STR_LIT("./lib/perl/libperl_bridge.so"); StradaValue *__call_result = strada_is_file(__call_arg0); strada_decref(__call_arg0); __call_result; }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
    { StradaValue *__retval = STRADA_NEW_STR_LIT("./lib/perl/libperl_bridge.so");
        strada_stack_pop();
        return __retval; }
}
if (({ StradaValue *__cond_tmp = ({ StradaValue *__call_arg0 = STRADA_NEW_STR_LIT("./cannoli/lib/perl/libperl_bridge.so"); StradaValue *__call_result = strada_is_file(__call_arg0); strada_decref(__call_arg0); __call_result; }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
    { StradaValue *__retval = STRADA_NEW_STR_LIT("./cannoli/lib/perl/libperl_bridge.so");
        strada_stack_pop();
        return __retval; }
}
if (({ StradaValue *__cond_tmp = ({ StradaValue *__call_arg0 = STRADA_NEW_STR_LIT("/usr/local/lib/cannoli/libperl_bridge.so"); StradaValue *__call_result = strada_is_file(__call_arg0); strada_decref(__call_arg0); __call_result; }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
    { StradaValue *__retval = STRADA_NEW_STR_LIT("/usr/local/lib/cannoli/libperl_bridge.so");
        strada_stack_pop();
        return __retval; }
}
{ StradaValue *__retval = STRADA_NEW_STR_LIT("libperl_bridge.so");
    strada_stack_pop();
    return __retval; }
strada_stack_pop();
return strada_new_undef();
}


StradaValue* find_cannoli_pm_path(void) {
strada_stack_push("find_cannoli_pm_path", "cannoli_perl.strada");
if (({ StradaValue *__cond_tmp = ({ StradaValue *__call_arg0 = STRADA_NEW_STR_LIT("./lib/perl/Cannoli.pm"); StradaValue *__call_result = strada_is_file(__call_arg0); strada_decref(__call_arg0); __call_result; }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
    { StradaValue *__retval = STRADA_NEW_STR_LIT("./lib/perl/Cannoli.pm");
        strada_stack_pop();
        return __retval; }
}
if (({ StradaValue *__cond_tmp = ({ StradaValue *__call_arg0 = STRADA_NEW_STR_LIT("./cannoli/lib/perl/Cannoli.pm"); StradaValue *__call_result = strada_is_file(__call_arg0); strada_decref(__call_arg0); __call_result; }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
    { StradaValue *__retval = STRADA_NEW_STR_LIT("./cannoli/lib/perl/Cannoli.pm");
        strada_stack_pop();
        return __retval; }
}
if (({ StradaValue *__cond_tmp = ({ StradaValue *__call_arg0 = STRADA_NEW_STR_LIT("/usr/local/lib/cannoli/Cannoli.pm"); StradaValue *__call_result = strada_is_file(__call_arg0); strada_decref(__call_arg0); __call_result; }); int __cond_res = strada_to_bool(__cond_tmp); strada_decref(__cond_tmp); __cond_res; })) {
    { StradaValue *__retval = STRADA_NEW_STR_LIT("/usr/local/lib/cannoli/Cannoli.pm");
        strada_stack_pop();
        return __retval; }
}
{ StradaValue *__retval = STRADA_NEW_STR_LIT("");
    strada_stack_pop();
    return __retval; }
strada_stack_pop();
return strada_new_undef();
}


StradaValue* cannoli_init(StradaValue* config) {
strada_stack_push("cannoli_init", "cannoli_perl.strada");
strada_incref(config);
strada_cleanup_push(config);
({ StradaValue *__old = g_handler_sub; g_handler_sub = ({ StradaValue *__arg1 = STRADA_NEW_STR_LIT("handler"); strada_stack_set_line(188); StradaValue *__call_result = config_get(config, __arg1); strada_decref(__arg1); __call_result; }); strada_decref(__old); g_handler_sub; });
if ((({ StradaValue *__num_tmp = ({ StradaValue *__len_tmp = g_handler_sub; int64_t __len_res = strada_length_chars_sv(__len_tmp); strada_new_int(__len_res); }); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }) == 0.0)) {
    ({ StradaValue *__say_tmp = STRADA_NEW_STR_LIT("cannoli_perl: ERROR - Missing required 'handler' parameter"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    ({ StradaValue *__say_tmp = STRADA_NEW_STR_LIT("Usage: --library ./cannoli_perl.so:handler=MyApp::handle"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_cleanup_pop();
        strada_decref(config);
        strada_stack_pop();
        return __retval; }
}
StradaValue *bridge_path = (strada_stack_set_line(196), find_bridge_path());
strada_cleanup_push(bridge_path);
({ StradaValue *__old = g_perl_bridge; g_perl_bridge = strada_dl_open(bridge_path); strada_decref(__old); g_perl_bridge; });
if ((strada_to_num(g_perl_bridge) == 0.0)) {
    ({ StradaValue *__say_tmp = strada_concat_cstr_sv("cannoli_perl: ERROR - Could not load ", 37, bridge_path); strada_say(__say_tmp); strada_decref(__say_tmp); });
    ({ StradaValue *__say_tmp = STRADA_NEW_STR_LIT("  Make sure libperl_bridge.so is built and accessible"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_cleanup_pop(); strada_decref(bridge_path);
        strada_cleanup_pop();
        strada_decref(config);
        strada_stack_pop();
        return __retval; }
}
({ StradaValue *__old = g_init_fn; g_init_fn = ({ StradaValue *__call_arg1 = STRADA_NEW_STR_LIT("perl_bridge_init"); StradaValue *__call_result = strada_dl_sym(g_perl_bridge, __call_arg1); strada_decref(__call_arg1); __call_result; }); strada_decref(__old); g_init_fn; });
({ StradaValue *__old = g_add_inc_fn; g_add_inc_fn = ({ StradaValue *__call_arg1 = STRADA_NEW_STR_LIT("perl_bridge_add_inc"); StradaValue *__call_result = strada_dl_sym(g_perl_bridge, __call_arg1); strada_decref(__call_arg1); __call_result; }); strada_decref(__old); g_add_inc_fn; });
({ StradaValue *__old = g_use_fn; g_use_fn = ({ StradaValue *__call_arg1 = STRADA_NEW_STR_LIT("perl_bridge_use"); StradaValue *__call_result = strada_dl_sym(g_perl_bridge, __call_arg1); strada_decref(__call_arg1); __call_result; }); strada_decref(__old); g_use_fn; });
({ StradaValue *__old = g_do_fn; g_do_fn = ({ StradaValue *__call_arg1 = STRADA_NEW_STR_LIT("perl_bridge_do"); StradaValue *__call_result = strada_dl_sym(g_perl_bridge, __call_arg1); strada_decref(__call_arg1); __call_result; }); strada_decref(__old); g_do_fn; });
({ StradaValue *__old = g_load_cannoli_fn; g_load_cannoli_fn = ({ StradaValue *__call_arg1 = STRADA_NEW_STR_LIT("perl_bridge_load_cannoli"); StradaValue *__call_result = strada_dl_sym(g_perl_bridge, __call_arg1); strada_decref(__call_arg1); __call_result; }); strada_decref(__old); g_load_cannoli_fn; });
({ StradaValue *__old = g_call_handler_fn; g_call_handler_fn = ({ StradaValue *__call_arg1 = STRADA_NEW_STR_LIT("perl_bridge_call_handler"); StradaValue *__call_result = strada_dl_sym(g_perl_bridge, __call_arg1); strada_decref(__call_arg1); __call_result; }); strada_decref(__old); g_call_handler_fn; });
if (((strada_to_num(g_init_fn) == 0.0) || (strada_to_num(g_call_handler_fn) == 0.0))) {
    ({ StradaValue *__say_tmp = STRADA_NEW_STR_LIT("cannoli_perl: ERROR - Bridge functions not found"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_cleanup_pop(); strada_decref(bridge_path);
        strada_cleanup_pop();
        strada_decref(config);
        strada_stack_pop();
        return __retval; }
}
StradaValue *init_result = ({ StradaValue *__call_arg1 = STRADA_NEW_STR_LIT("init"); StradaValue *__call_result = strada_dl_call_int(g_init_fn, __call_arg1); strada_decref(__call_arg1); __call_result; });
strada_cleanup_push(init_result);
if ((strada_to_int(init_result) == 0)) {
    ({ StradaValue *__say_tmp = STRADA_NEW_STR_LIT("cannoli_perl: ERROR - Perl initialization failed"); strada_say(__say_tmp); strada_decref(__say_tmp); });
    { StradaValue *__retval = strada_new_int(0);
        strada_cleanup_pop(); strada_decref(bridge_path);
        strada_cleanup_pop(); strada_decref(init_result);
        strada_cleanup_pop();
        strada_decref(config);
        strada_stack_pop();
        return __retval; }
}
StradaValue *lib_paths = ({ StradaValue *__arg1 = STRADA_NEW_STR_LIT("lib"); strada_stack_set_line(226); StradaValue *__call_result = config_get_all(config, __arg1); strada_decref(__arg1); __call_result; });
strada_cleanup_push(lib_paths);
StradaValue *i = strada_new_int(0);
strada_cleanup_push(i);
while ((strada_to_num(i) < ({ StradaValue *__num_tmp = strada_new_int(strada_array_length(strada_deref_array(lib_paths))); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }))) {
    __redo_8: __attribute__((unused));
    StradaValue *lib_path = strada_array_get(strada_deref_array(lib_paths), strada_to_int(i)); strada_incref(lib_path);
    strada_cleanup_push(lib_path);
    ({ StradaValue *__dl_args = strada_anon_array(1, lib_path); StradaValue *__dl_res = strada_dl_call_int_sv(g_add_inc_fn, __dl_args); strada_decref(__dl_args); __dl_res; });
    ({ StradaValue *__old = i; i = STRADA_MAKE_TAGGED_INT(strada_to_int(i) + 1); strada_decref(__old); i; });
    strada_break_self_cycle(lib_path);
    strada_cleanup_pop(); strada_decref(lib_path);
}
({ StradaValue *__old = g_cannoli_pm_path; g_cannoli_pm_path = (strada_stack_set_line(235), find_cannoli_pm_path()); strada_decref(__old); g_cannoli_pm_path; });
if ((strada_to_num(g_load_cannoli_fn) != 0.0)) {
    StradaValue *load_result = ({ StradaValue *__dl_args = strada_anon_array(1, g_cannoli_pm_path); StradaValue *__dl_res = strada_dl_call_int_sv(g_load_cannoli_fn, __dl_args); strada_decref(__dl_args); __dl_res; });
    strada_cleanup_push(load_result);
    if ((strada_to_int(load_result) == 0)) {
        ({ StradaValue *__say_tmp = STRADA_NEW_STR_LIT("cannoli_perl: ERROR - Failed to load Cannoli.pm"); strada_say(__say_tmp); strada_decref(__say_tmp); });
        { StradaValue *__retval = strada_new_int(0);
            strada_cleanup_pop(); strada_decref(load_result);
            strada_cleanup_pop(); strada_decref(bridge_path);
            strada_cleanup_pop(); strada_decref(init_result);
            strada_cleanup_pop(); strada_decref(lib_paths);
            strada_cleanup_pop(); strada_decref(i);
            strada_cleanup_pop();
            strada_decref(config);
            strada_stack_pop();
            return __retval; }
    }
    strada_break_self_cycle(load_result);
    strada_cleanup_pop(); strada_decref(load_result);
}
StradaValue *modules = ({ StradaValue *__arg1 = STRADA_NEW_STR_LIT("use"); strada_stack_set_line(245); StradaValue *__call_result = config_get_all(config, __arg1); strada_decref(__arg1); __call_result; });
strada_cleanup_push(modules);
({ StradaValue *__old = i; i = strada_new_int(0); strada_decref(__old); i; });
while ((strada_to_num(i) < ({ StradaValue *__num_tmp = strada_new_int(strada_array_length(strada_deref_array(modules))); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }))) {
    __redo_9: __attribute__((unused));
    StradaValue *module = strada_array_get(strada_deref_array(modules), strada_to_int(i)); strada_incref(module);
    strada_cleanup_push(module);
    StradaValue *use_result = ({ StradaValue *__dl_args = strada_anon_array(1, module); StradaValue *__dl_res = strada_dl_call_int_sv(g_use_fn, __dl_args); strada_decref(__dl_args); __dl_res; });
    strada_cleanup_push(use_result);
    if ((strada_to_int(use_result) == 0)) {
        ({ StradaValue *__say_tmp = strada_concat_cstr_sv("cannoli_perl: ERROR - Failed to use ", 36, module); strada_say(__say_tmp); strada_decref(__say_tmp); });
        { StradaValue *__retval = strada_new_int(0);
            strada_cleanup_pop(); strada_decref(module);
            strada_cleanup_pop(); strada_decref(use_result);
            strada_cleanup_pop(); strada_decref(bridge_path);
            strada_cleanup_pop(); strada_decref(init_result);
            strada_cleanup_pop(); strada_decref(lib_paths);
            strada_cleanup_pop(); strada_decref(i);
            strada_cleanup_pop(); strada_decref(modules);
            strada_cleanup_pop();
            strada_decref(config);
            strada_stack_pop();
            return __retval; }
    }
    ({ StradaValue *__old = i; i = STRADA_MAKE_TAGGED_INT(strada_to_int(i) + 1); strada_decref(__old); i; });
    strada_break_self_cycle(module);
    strada_break_self_cycle(use_result);
    strada_cleanup_pop(); strada_decref(module);
    strada_cleanup_pop(); strada_decref(use_result);
}
StradaValue *script = ({ StradaValue *__arg1 = STRADA_NEW_STR_LIT("script"); strada_stack_set_line(258); StradaValue *__call_result = config_get(config, __arg1); strada_decref(__arg1); __call_result; });
strada_cleanup_push(script);
if ((({ StradaValue *__num_tmp = ({ StradaValue *__len_tmp = script; int64_t __len_res = strada_length_chars_sv(__len_tmp); strada_new_int(__len_res); }); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }) > 0.0)) {
    StradaValue *do_result = ({ StradaValue *__dl_args = strada_anon_array(1, script); StradaValue *__dl_res = strada_dl_call_int_sv(g_do_fn, __dl_args); strada_decref(__dl_args); __dl_res; });
    strada_cleanup_push(do_result);
    if ((strada_to_int(do_result) == 0)) {
        ({ StradaValue *__say_tmp = strada_concat_cstr_sv("cannoli_perl: ERROR - Failed to load ", 37, script); strada_say(__say_tmp); strada_decref(__say_tmp); });
        { StradaValue *__retval = strada_new_int(0);
            strada_cleanup_pop(); strada_decref(do_result);
            strada_cleanup_pop(); strada_decref(bridge_path);
            strada_cleanup_pop(); strada_decref(init_result);
            strada_cleanup_pop(); strada_decref(lib_paths);
            strada_cleanup_pop(); strada_decref(i);
            strada_cleanup_pop(); strada_decref(modules);
            strada_cleanup_pop(); strada_decref(script);
            strada_cleanup_pop();
            strada_decref(config);
            strada_stack_pop();
            return __retval; }
    }
    strada_break_self_cycle(do_result);
    strada_cleanup_pop(); strada_decref(do_result);
}
{ StradaValue *__retval = strada_new_int(1);
    strada_cleanup_pop(); strada_decref(bridge_path);
    strada_cleanup_pop(); strada_decref(init_result);
    strada_cleanup_pop(); strada_decref(lib_paths);
    strada_cleanup_pop(); strada_decref(i);
    strada_cleanup_pop(); strada_decref(modules);
    strada_cleanup_pop(); strada_decref(script);
    strada_cleanup_pop();
    strada_decref(config);
    strada_stack_pop();
    return __retval; }
strada_break_self_cycle(bridge_path);
strada_break_self_cycle(init_result);
strada_break_self_cycle(lib_paths);
strada_break_self_cycle(i);
strada_break_self_cycle(modules);
strada_break_self_cycle(script);
strada_cleanup_pop(); strada_decref(bridge_path);
strada_cleanup_pop(); strada_decref(init_result);
strada_cleanup_pop(); strada_decref(lib_paths);
strada_cleanup_pop(); strada_decref(i);
strada_cleanup_pop(); strada_decref(modules);
strada_cleanup_pop(); strada_decref(script);
strada_cleanup_pop();
strada_decref(config);
strada_stack_pop();
return strada_new_undef();
}


StradaValue* cannoli_dispatch(StradaValue* c) {
strada_stack_push("cannoli_dispatch", "cannoli_perl.strada");
strada_incref(c);
strada_cleanup_push(c);
if (((strada_to_num(g_call_handler_fn) == 0.0) || (({ StradaValue *__num_tmp = ({ StradaValue *__len_tmp = g_handler_sub; int64_t __len_res = strada_length_chars_sv(__len_tmp); strada_new_int(__len_res); }); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }) == 0.0))) {
    { StradaValue *__retval = STRADA_NEW_STR_LIT("");
        strada_cleanup_pop();
        strada_decref(c);
        strada_stack_pop();
        return __retval; }
}
StradaValue *method = strada_hv_fetch_owned(c, "_method");
strada_cleanup_push(method);
StradaValue *path = strada_hv_fetch_owned(c, "_path");
strada_cleanup_push(path);
StradaValue *path_info = strada_hv_fetch_owned(c, "_path_info");
strada_cleanup_push(path_info);
StradaValue *query_string = strada_hv_fetch_owned(c, "_query_string");
strada_cleanup_push(query_string);
StradaValue *body = strada_hv_fetch_owned(c, "_body");
strada_cleanup_push(body);
StradaValue *remote_addr = strada_hv_fetch_owned(c, "_remote_addr");
strada_cleanup_push(remote_addr);
StradaValue *content_type = strada_hv_fetch_owned(c, "_content_type");
strada_cleanup_push(content_type);
StradaValue *headers = STRADA_NEW_STR_LIT("");
strada_cleanup_push(headers);
StradaValue *hdrs = strada_hv_fetch_owned(c, "_headers");
strada_cleanup_push(hdrs);
if (strada_defined_bool(hdrs)) {
    StradaValue *hdr_names = strada_new_array_from_av(strada_hash_keys(strada_deref_hash(strada_deref_hash_value(hdrs))));
    strada_cleanup_push(hdr_names);
    StradaValue *i = strada_new_int(0);
    strada_cleanup_push(i);
    while ((strada_to_num(i) < ({ StradaValue *__num_tmp = strada_new_int(strada_array_length(strada_deref_array(hdr_names))); double __num_val = strada_to_num(__num_tmp); strada_decref(__num_tmp); __num_val; }))) {
        __redo_10: __attribute__((unused));
        StradaValue *hn = strada_array_get(strada_deref_array(hdr_names), strada_to_int(i)); strada_incref(hn);
        strada_cleanup_push(hn);
        StradaValue *hv = ({ StradaValue *__hget_k = hn; StradaValue *__hget_r = strada_hv_fetch_owned_sv(hdrs, __hget_k); __hget_r; });
        strada_cleanup_push(hv);
        ({ StradaValue *__old = headers; headers = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = ({ StradaValue *__concat_l = strada_concat_sv(headers, hn); strada_concat_inplace_cstr(__concat_l, ": ", 2); }); strada_cleanup_push(__concat_l); strada_cleanup_pop(); strada_concat_inplace(__concat_l, hv); }); strada_concat_inplace_cstr(__concat_l, "\r\n", 2); }); strada_decref(__old); headers; });
        ({ StradaValue *__old = i; i = STRADA_MAKE_TAGGED_INT(strada_to_int(i) + 1); strada_decref(__old); i; });
        strada_break_self_cycle(hn);
        strada_break_self_cycle(hv);
        strada_cleanup_pop(); strada_decref(hn);
        strada_cleanup_pop(); strada_decref(hv);
    }
    strada_break_self_cycle(hdr_names);
    strada_break_self_cycle(i);
    strada_cleanup_pop(); strada_decref(hdr_names);
    strada_cleanup_pop(); strada_decref(i);
}
StradaValue *result = ({ StradaValue *__dl_args = strada_anon_array(9, g_handler_sub, method, path, path_info, query_string, body, headers, remote_addr, content_type); StradaValue *__dl_res = strada_dl_call_str_sv(g_call_handler_fn, __dl_args); strada_decref(__dl_args); __dl_res; });
strada_cleanup_push(result);
{ StradaValue *__retval = result;
    strada_incref(__retval);
    strada_cleanup_pop(); strada_decref(method);
    strada_cleanup_pop(); strada_decref(path);
    strada_cleanup_pop(); strada_decref(path_info);
    strada_cleanup_pop(); strada_decref(query_string);
    strada_cleanup_pop(); strada_decref(body);
    strada_cleanup_pop(); strada_decref(remote_addr);
    strada_cleanup_pop(); strada_decref(content_type);
    strada_cleanup_pop(); strada_decref(headers);
    strada_cleanup_pop(); strada_decref(hdrs);
    strada_cleanup_pop(); strada_decref(result);
    strada_cleanup_pop();
    strada_decref(c);
    strada_stack_pop();
    return __retval; }
strada_break_self_cycle(method);
strada_break_self_cycle(path);
strada_break_self_cycle(path_info);
strada_break_self_cycle(query_string);
strada_break_self_cycle(body);
strada_break_self_cycle(remote_addr);
strada_break_self_cycle(content_type);
strada_break_self_cycle(headers);
strada_break_self_cycle(hdrs);
strada_break_self_cycle(result);
strada_cleanup_pop(); strada_decref(method);
strada_cleanup_pop(); strada_decref(path);
strada_cleanup_pop(); strada_decref(path_info);
strada_cleanup_pop(); strada_decref(query_string);
strada_cleanup_pop(); strada_decref(body);
strada_cleanup_pop(); strada_decref(remote_addr);
strada_cleanup_pop(); strada_decref(content_type);
strada_cleanup_pop(); strada_decref(headers);
strada_cleanup_pop(); strada_decref(hdrs);
strada_cleanup_pop(); strada_decref(result);
strada_cleanup_pop();
strada_decref(c);
strada_stack_pop();
return strada_new_undef();
}



/* Strada export metadata for import_lib */
const char* __strada_export_info(void) {
    return "func:config_get:str:2:str,str:-1\nfunc:config_get_all:array:2:str,str:-1\nfunc:find_bridge_path:str:0::-1\nfunc:find_cannoli_pm_path:str:0::-1\nfunc:cannoli_init:int:1:str:-1\nfunc:cannoli_dispatch:str:1:scalar:-1\n";
}

/* Strada module version */
const char* __strada_version(void) {
    return "";
}

/* Shared library global initialization */
__attribute__((constructor))
static void __strada_init_globals(void) {
    if (g_perl_bridge == NULL) {
        g_perl_bridge = strada_new_int(0);
    }
    if (g_handler_sub == NULL) {
        g_handler_sub = STRADA_NEW_STR_LIT("");
    }
    if (g_cannoli_pm_path == NULL) {
        g_cannoli_pm_path = STRADA_NEW_STR_LIT("");
    }
    if (g_init_fn == NULL) {
        g_init_fn = strada_new_int(0);
    }
    if (g_add_inc_fn == NULL) {
        g_add_inc_fn = strada_new_int(0);
    }
    if (g_use_fn == NULL) {
        g_use_fn = strada_new_int(0);
    }
    if (g_do_fn == NULL) {
        g_do_fn = strada_new_int(0);
    }
    if (g_load_cannoli_fn == NULL) {
        g_load_cannoli_fn = strada_new_int(0);
    }
    if (g_call_handler_fn == NULL) {
        g_call_handler_fn = strada_new_int(0);
    }
}
